# https://dependabot.com/docs/config-file/#dependabot-config-files
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
# Uncomment if we enable auto-merging
#    automerged_updates:
#      - match:
#          dependency_type: "all"
#          update_type: "all"
