
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: syncedsecrets.secrets.contentful.com
spec:
  group: secrets.contentful.com
  names:
    kind: SyncedSecret
    listKind: SyncedSecretList
    plural: syncedsecrets
    singular: syncedsecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SyncedSecret is the Schema for the SyncedSecrets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SyncedSecretSpec defines the desired state of SyncedSecret
          properties:
            IAMRole:
              description: IAMRole
              type: string
            data:
              description: Data
              items:
                properties:
                  name:
                    type: string
                  value:
                    description: Value
                    type: string
                  valueFrom:
                    description: ValueFrom
                    properties:
                      secretKeyRef:
                        description: SecretKeyRef
                        properties:
                          key:
                            type: string
                          name:
                            type: string
                        required:
                        - key
                        - name
                        type: object
                      secretRef:
                        description: SecretRef
                        properties:
                          name:
                            type: string
                        required:
                        - name
                        type: object
                      template:
                        description: Template
                        type: string
                    type: object
                required:
                - name
                type: object
              type: array
            dataFrom:
              description: DataFrom
              properties:
                secretRef:
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
              type: object
            secretMetadata:
              description: Secret Metadata
              type: object
            type:
              description: Type
              type: string
          type: object
        status:
          description: SyncedSecretStatus defines the observed state of SyncedSecret
          properties:
            currentVersionID:
              description: this is the version of the secret that is present in k8s
                secret this should be coming from the local cache
              type: string
            generatedSecretHash:
              description: hash(secret.data) that was generated, used for checking
                of a Secret has diverged and if it needs reconciling
              type: string
          required:
          - currentVersionID
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
